name: MSBuild

on:
  pull_request:
    types: [synchronize, opened]
    
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - run: |
          msbuild -version

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
